export const Constants = {
    NR_OF_RESULTS_PER_PAGE: 12,

    RATING_POSITIVE_FACTOR: 1,
    RATING_NEGATIVE_FACTOR: -1.1,
    RATING_MIN: 0,
    RATING_MIN_AUTO_SKIP: 2.5,
    RATING_DIFF: 2.1,
    RATING_BOOST: 1.3,
    RATING_BOOST_TIME: 604800000, // 7 days

    RATING_POSITIVE_FACTOR_TRUST_SCORE: 1,
    RATING_NEGATIVE_FACTOR_TRUST_SCORE: -1.7,
    RATING_POSITIVE_FACTOR_TRUST_SCORE_ADMIN: 5,
    RATING_NEGATIVE_FACTOR_TRUST_SCORE_ADMIN: -8,
};
